//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;
import calculatorMain.*;

class calculatorLogic extends Calculator {

}

public class CalculatorGUI extends JFrame {
    private JTextField resultBar;
    private JButton prev;
    private JButton next;
    private JButton add;
    private JButton sub;
    private JButton mul;
    private JButton div;
    private JButton k0;
    private JButton k1;
    private JButton k2;
    private JButton k3;
    private JButton k4;
    private JButton k7;
    private JButton k5;
    private JButton k6;
    private JButton k8;
    private JButton k9;
    private JButton madd;
    private JButton mr;
    private JButton mc;
    private JButton clean;
    private JButton fullClean;
    String numberText = "";

    public CalculatorGUI(String title) {
        super(title);
    }

    public CalculatorGUI(){}

    public void setComponents() {
        //construct components
        resultBar = new JTextField (5);
        prev = new JButton ("<");
        next = new JButton (">");
        add = new JButton ("+");
        sub = new JButton ("-");
        mul = new JButton ("x");
        div = new JButton ("%");
        k0 = new JButton ("0");
        k1 = new JButton ("1");
        k2 = new JButton ("2");
        k3 = new JButton ("3");
        k4 = new JButton ("4");
        k7 = new JButton ("7");
        k5 = new JButton ("5");
        k6 = new JButton ("6");
        k8 = new JButton ("8");
        k9 = new JButton ("9");
        madd = new JButton ("M+");//m+,mr,mc
        mr = new JButton("Mr");
        mc = new JButton("Mc");
        clean = new JButton ("C");
        fullClean = new JButton ("AC");

        //adjust size and set layout
        setPreferredSize (new Dimension (624, 329));
        setLayout (null);

        //add components
        add (resultBar);
        add (prev);
        add (next);
        add (add);
        add (sub);
        add (mul);
        add (div);
        add (k0);
        add (k1);
        add (k2);
        add (k3);
        add (k4);
        add (k7);
        add (k5);
        add (k6);
        add (k8);
        add (k9);
        add (madd);
        add (mr);
        add (mc);
        add (clean);
        add (fullClean);

        //set component bounds (only needed by Absolute Positioning)
        resultBar.setBounds (30, 25, 565, 40);
        prev.setBounds (25, 90, 45, 35);
        next.setBounds (75, 90, 45, 35);
        add.setBounds (50, 265, 45, 40);
        add.addActionListener(new Handler());
        sub.setBounds (50, 220, 45, 40);
        sub.addActionListener(new Handler());
        mul.setBounds (50, 175, 45, 40);
        mul.addActionListener(new Handler());
        div.setBounds (50, 130, 45, 40);
        div.addActionListener(new Handler());
        k0.setBounds (405, 260, 45, 40);
        k0.addActionListener(new Handler());
        k1.setBounds (350, 215, 45, 40);
        k1.addActionListener(new Handler());
        k2.setBounds (405, 215, 45, 40);
        k2.addActionListener(new Handler());
        k3.setBounds (460, 215, 45, 40);
        k3.addActionListener(new Handler());
        k4.setBounds (350, 165, 45, 40);
        k4.addActionListener(new Handler());
        k7.setBounds (350, 115, 45, 40);
        k7.addActionListener(new Handler());
        k5.setBounds (405, 165, 45, 40);
        k5.addActionListener(new Handler());
        k6.setBounds (460, 165, 45, 40);
        k6.addActionListener(new Handler());
        k8.setBounds (410, 115, 45, 40);
        k8.addActionListener(new Handler());
        k9.setBounds (460, 115, 45, 40);
        k9.addActionListener(new Handler());
        madd.setBounds (320, 70, 60, 40);
        mr.setBounds (400, 70, 60, 40);
        mc.setBounds (480, 70, 60, 40);
        clean.setBounds (545, 130, 55, 45);
        clean.addActionListener(new Handler());
        fullClean.setBounds (545, 190, 55, 45);
        fullClean.addActionListener(new Handler());
        resultBar.setEditable(false);
    }


    class Handler implements ActionListener {
        @Override
          public void actionPerformed(ActionEvent e) {
            //number button actions
            if (e.getSource() == k0) {
                numberText += "0";
                resultBar.setText(numberText);
            }
            else if (e.getSource() == k1) {
                numberText += "1";
                resultBar.setText(numberText);
            }
            else if (e.getSource() == k2) {
                numberText += "2";
                resultBar.setText(numberText);
            }
            else if (e.getSource() == k3) {
                numberText += "3";
                resultBar.setText(numberText);
            }
            else if (e.getSource() == k4) {
                numberText += "4";
                resultBar.setText(numberText);
            }
            else if (e.getSource() == k5) {
                numberText += "5";
                resultBar.setText(numberText);
            }
            else if (e.getSource() == k6) {
                numberText += "6";
                resultBar.setText(numberText);
            }
            else if (e.getSource() == k7) {
                numberText += "7";
                resultBar.setText(numberText);
            }else if (e.getSource() == k8) {
                numberText += "8";
                resultBar.setText(numberText);
            }
            else if (e.getSource() == k9) {
                numberText += "9";
                resultBar.setText(numberText);
            }
          //clear button actions
            else if (e.getSource() == clean) {
                String temp = resultBar.getText();
                if(temp.length()!=0) {
                    numberText = temp.substring(0, temp.length() - 1);
                    resultBar.setText(numberText);
                }
            }
            else if (e.getSource() == fullClean) {
                numberText = "";
                resultBar.setText(numberText);
            }
          //operation button actions
          //memory button actions
        }

        int operations(char op, int ord1, int ord2) {
            switch(op) {
                case '+':
                    return ord1 + ord2;
                case '-':
                    return ord1 - ord2;
                case 'x':
                    return ord1 * ord2;
                case '%':
                    return ord1 / ord2;
            }
            return 0;
        }
      }

    public static void main (String[] args) {
        CalculatorGUI calculator = new CalculatorGUI("Calculator");
        calculatorLogic logic = new calculatorLogic();
        calculator.setComponents();
        calculator.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        calculator.pack();
        calculator.setVisible(true);
    }
}
